### ISSUE TITLE
Design: improve UI of the app

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/playtify#13]
### Description:
Enhance the app's navigation by adding a bottom navigation bar with two primary tabs: "Dashboard" and "Playlist Add/Remove View". Also create a Dashboard UI, which includes a textbox for entering a genre or mood and a button to initiate playlist selection.

### Tips for the issue:
- feel free to give a new look to the app

### To do:
- [x] Ask us to assign the issue.
- [x] Once the issue is assigned, you can start working on it.
- [x] Create a PR
 
### Resources:
- [Flutter Docs on Navigation](https://docs.flutter.dev/ui/navigation)
- [Flutter app UI Docs](https://docs.flutter.dev/ui)

### Note:
The task is **assigned to contributors on a first-come, first-serve basis**, and the contributor has to **report progress every 3 days** to ensure active development on the tasks. If you need any help feel free to tag and message

**Comment by D-extremity** [comment]
1.) do we need to make bottom app bar like instagram , 1st for Dashboard and 2nd for Playlist?

**Comment by dk-a-dev** [comment]
@D-extremity yup that's the idea I have 
Feel free to change ui, come up with something better, also keep me in the loop whatever changes you do..
You can Start working this issue is urs now
Happy coding ❤️

**Comment by D-extremity** [comment]
@dk-a-dev merge it please 🙌🏻✨

**Comment by dk-a-dev** [comment]
@D-extremity yup bro, i was little busy :) exams:(
I currently reviewing will merge it dw

**Comment by D-extremity** [comment]
@dk-a-dev okay okay ༎ຶ‿༎ຶ actually I also have exams from tomorrow that's why I am in panick mode ....
Okay no issue merge it asap🙌🏻✨
