### ISSUE TITLE
Refactor: adding flutter linter rules

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/playtify#16]
### Description:
The addition of linter rules to our Flutter project to ensure code quality and maintainability. Linter rules can help us catch potential issues early in the development process and maintain a consistent coding style.

### Tips for the issue:
- Research and identify a set of Flutter-specific linting rules that align with best practices and our project's goals.
- Configure the selected linter rules in our project, ensuring they are compatible with our current codebase.
- Improve the overall code quality and maintainability of our Flutter project.

### To do:
- [ ] Ask us to assign the issue
- [ ] Once the issue is assigned, you can start working on it
- [ ] Create a PR

### Resources:
- [dart/linter-rules](https://dart.dev/tools/linter-rules)
- [package/flutter-lints](https://pub.dev/packages/flutter_lints)

### Note:
The task is **assigned to contributors on a first-come, first-serve basis**, and the **contributor has to report progress every 3 days** to ensure active development on the tasks.

**Comment by RitwikSingh28** [comment]
@dk-a-dev 
Please assign this issue to me.

**Comment by dk-a-dev** [comment]
@RitwikSingh28 ye sure it's assigned, please stick to the note mentioned
