### ISSUE TITLE
Feature: creating interactive home-screen

### ISSUE THREAD

**Issue by pranjalsingh03** [IEEE-VIT/playtify#19]

**Comment by pranjalsingh03** [comment]
Please assign me this so that I could make the interactive Ui for homescreen using dart

**Comment by dk-a-dev** [comment]
@pranjalsingh03 Please elaborate the issue in proper terms

**Comment by pranjalsingh03** [comment]
i want to change the appearance of the home page

**Comment by dk-a-dev** [comment]
ok get it, work on it, i am assigning this to you

**Comment by dk-a-dev** [comment]
@pranjalsingh03 what ideas u have in mind
do share with me

**Comment by pranjalsingh03** [comment]
i will be adding the options like recently played in the formate of carousel slider and featured playlist and will be adding the daily mix section also

**Comment by pranjalsingh03** [comment]
I am using the dark theme for the app

**Comment by dk-a-dev** [comment]
Not needed now
