### ISSUE TITLE
Issue 3:- Create dashboard UI (textbox and button)

### ISSUE THREAD

**Issue by shubhbansal9** [IEEE-VIT/playtify#3]
- Create the dashboard UI which includes a textbox and a button.
- The textbox is where the user shall enter their genre/mood.
- The button will be pressed by the user after his entry in the textbox so it should take them to the final screen where their randomly selected playlist based on their mood is displayed.

**Comment by Harmanjaggi** [comment]
Hi, Can I work on this issue?

**Comment by laksh29** [comment]
heyy @shubhbansal9 !
Is this issue still open ?? I'd like to contribute to it

**Comment by D-extremity** [comment]
@shubhbansal9 please assign me this issue
